baseURL = 'https://min47p.github.io/blog-demo/'
languageCode = 'en-us'
title = 'My Blog'

[pagination]
  pagerSize = 10

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true

  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
      strikethrough = true
      table = true
      taskList = true

      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true

      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\[', '\]']]
          inline = [['$', '$'], ['\(', '\)']]

    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = 'A blog.'
  author = 'min47p'
  katexVersion = '0.16'

[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menus.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 2
